amazon_seller/urls.py
from django.conf.urls import url
from .views import setupSellerAccount, home, profile, updateuser, remove, subscription_page, cancelSubscription, help_page, upgrade, setupEbayAccount
from orders.views import OrdersListView

urlpatterns = [
    url(r'^setup/$', setupSellerAccount, name='setup'),
    url(r'^home/$', home, name='home'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^updateuser/$', updateuser, name='updateuser'),
    url(r'^orders/$', OrdersListView.as_view(), name='orders'),
    url(r'^remove/$', remove, name='remove'),
    url(r'^subscription/$', subscription_page, name='subscription'),
    url(r'^subscription/cancel$', cancelSubscription, name='cancelSubscription'),
    url(r'^help$', help_page, name='help'),
    url(r'^ebay$', setupEbayAccount, name='ebay'),
    #url(r'^upgrade$', upgrade, name='upgrade'),
]

buyers/urls.py
from django.conf.urls import url
from orders.views import OrdersSearchView
from .views import learn_more, contact_page, search_tool_page

urlpatterns = [
    #url(r'^contact/$', contact_page, name='contact'),
    url(r'^home/$', OrdersSearchView.as_view(), name='home'),
    url(r'^learnmore/$', learn_more, name='learn_more'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^searchTool/$', search_tool_page, name='search_tool'),
]

trackbot/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^amazon/', include(("amazon_seller.urls", "amazon"), namespace='amazon')),
    url(r'^buyers/', include(("buyers.urls", "buyers"), namespace='buyers')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include(('payment.urls', 'payment'), namespace='payment')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon_seller/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class SellerAccount(models.Model):
    user     = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    email    = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.email

class EbayAccount(models.Model):
    user    = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    activate = models.BooleanField()

    def __str__(self):
        return self.user.email

amazon_seller/forms.py
from django import forms

class AmazonLoginForm(forms.Form):
    email_widget = forms.TextInput(
        attrs={'type': 'email','placeholder':('E-mail address'), 'autofocus': 'autofocus', 'class': 'form-control'}
    )
    email = forms.EmailField(label=(""), widget=email_widget)

    password_widget = forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    )
    password = forms.CharField(label=(""), widget=password_widget)

amazon_seller/views.py
from django.shortcuts import render, redirect, reverse
from .models import SellerAccount, EbayAccount
from django.http import HttpResponse
from .forms import AmazonLoginForm
from .models import SellerAccount
from django.contrib.auth import get_user_model
from paypal.standard.forms import PayPalPaymentsForm
from payment.models import Transactions
from django.utils import timezone
from payment.utils import checkSubscription
from payment.models import Transactions
from datetime import timedelta
from collections import defaultdict
from django.core.mail import send_mail

def upgrade(request):
    pass

def help_page(request):
    if request.user.is_authenticated:
        if request.POST:
            tba = request.POST.get('tba_no')
            #message = 'Following tracking number of '+request.user.email+' is missing: '+tba
            # send_mail(
            #     'Re. Tracking Number',
            #     message,
            #     'wjeff.fortin@yahoo.com',
            #     ['info@beezytrack.com'],
            #     fail_silently=False,
            #     auth_user='wjeff.fortin@yahoo.com',
            #     auth_password='Beezytrack'
            # )
        return render(request, 'seller/help.html', {})
    return redirect('/accounts/login')

def remove(request):
    if request.user.is_authenticated:
        account = SellerAccount.objects.filter(user=request.user)
        if account:
            account.delete()
            return redirect('/amazon/setup')
    return redirect('/amazon/setup')

def profile(request):
    if request.user.is_authenticated:
        context = {}
        user = request.user
        context['Username'] = { 'label': user.username, 'code': 'username' }
        context['Email'] = {'label': user.email, 'code': 'email' }
        context['First Name'] = { 'label': user.first_name, 'code': 'first_name' }
        context['Last Name'] = { 'label': user.last_name, 'code': 'last_name' }
        return render(request, 'seller/profile.html', {'obj_list' : context})
    else:
        return redirect('/accounts/login')

def updateuser(request):
    if request.user.is_authenticated and request.is_ajax:
        user = request.user
        for key, values in request.POST.items():
            setattr(user, key, values)
            user.save()
        return HttpResponse('Done')
    else:
        return redirect('/accounts/login')

def setupSellerAccount(request):
    if request.user.is_authenticated:
        if request.session.get('subscribed'):
            form = AmazonLoginForm(request.POST or None)
        else:
            form = False
        context = {}
        account = SellerAccount.objects.filter(user=request.user)
        create = True
        if account:
            create = False
            context['email'] = account[0].email
        if request.POST and request.session.get('subscribed'):
            if form.is_valid():
                print(form.cleaned_data)
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')
                obj = SellerAccount.objects.get_or_create(
                    user = request.user,
                    email = email,
                    password = password
                )
                return redirect('/amazon/setup')
        context['form'] = form
        context['create'] = create
        inst = EbayAccount.objects.filter(user = request.user)
        if inst:
            context['ebayActive'] = True
        return render(request, 'seller/addThirdPartyAccounts.html', context)
    else:
        return redirect('/accounts/login')

def setupEbayAccount(request):
    if request.user.is_authenticated:
        context = {}
        if request.POST:
            obj = EbayAccount(
                user = request.user,
                activate = True
            )
            obj.save()
            context['notify'] = True
        if request.session.get('subscribed'):
            form = AmazonLoginForm(request.POST or None)
        else:
            form = False
        account = SellerAccount.objects.filter(user=request.user)
        create = True
        if account:
            create = False
            context['email'] = account[0].email
        context['form'] = form
        context['create'] = create
        inst = EbayAccount.objects.filter(user = request.user)
        if inst:
            context['ebayActive'] = True
        return render(request, 'seller/addThirdPartyAccounts.html', context)
    else:
        return redirect('/accounts/login')

def home(request):
    if request.user.is_authenticated:
        context = {}
        qs = Transactions.objects.filter(user = request.user)
        context['object_list'] = qs
        return render(request, 'seller/home.html', context)
    else:
        return redirect('/accounts/login')

def subscription_page(request):
    if request.user.is_authenticated:
        form = {}
        plans = {
            'Beezytrack': {
                'mo': 4.99,
                'yr': 49.99
            },
            'Pro Drop Shipper': {
                'mo': 4.99,
                'yr': 49.99
            },
            'Combo (Beezytrack + Pro Drop Shipper)': {
                'mo': 9.98,
                'yr': 99.98
            }
        }
        result = checkSubscription(request)
        if result.get('status'):
            obj = result.get('transaction')
            duration_int = result.get('duration')
            flag=0
            if duration_int == 30:
                duration_str = 'mo'
            elif duration_int == 365:
                duration_str = 'yr'
            for planName, attrs in plans.items():
                temp = {}
                for duration, amount in attrs.items():
                    if obj.plan == planName and duration_str == duration:
                        temp[duration] = {'status': True, 'amount': {'value': amount}, 'sandbox': "active", 'daysLeft': result.get('days-left'), 'daysPercent': (duration_int - result.get('days-left'))/duration_int*100 }
                        flag=1
                    else:
                        temp[duration] = {'status': False, 'sandbox': '', 'amount': {'value': amount}}
                if flag:
                    temp['active'] = duration_int
                    flag = 0
                form[planName] = temp
        else:
            for planName, attrs in plans.items():
                temp = {}
                for duration, amount in attrs.items():
                    paypal_dict = {
                        'business': 'nikhil.thakur929@gmail.com',
                        'amount': amount,
                        'item_name': planName,
                        'invoice': duration, # it should be unique
                        'currency_code': 'USD',
                        'notify_url': request.build_absolute_uri(reverse('paypal-ipn')),
                        'return_url': request.build_absolute_uri(reverse('payment:done')),
                        'cancel_return': request.build_absolute_uri(reverse('payment:cancelled')),
                        'rm': 2,
                        'custom': request.user.email
                    }
                    temp[duration] = (PayPalPaymentsForm(initial=paypal_dict))
                form[planName] = temp
        return render(request, "seller/subscription.html", {'form': form})
    else:
        return redirect('/accounts/login')

def cancelSubscription(request):
    if request.user.is_authenticated and request.session.get('subscribed') == True:
        user = request.user
        qs = Transactions.objects.filter(user=user, active=True)[0]
        setattr(qs, 'active', False)
        qs.save()
        return redirect('/amazon/subscription')
    else:
        return redirect('/accounts/login')

amazon_seller/templates/seller/addThirdPartyAccounts.html
{% extends './base.html' %}
{% load static %}
    {% block main %}
      <div class="container">
        {% if notify %}
          <div class="row">
            <div class="alert alert-success" role="alert">
              Successfullty activated ebay international tracking
            </div>
          </div>
        {% endif %}
        <div class="row">
          <div class="col text-center mt-5">
            <h1>Set up your seller account</h1>
            <h6>
              Link your Amazon Seller account so that you can start tracking your shipments.
              <br>To track your eBay International Shipments, tick the box below.
            </h6>
          </div>
        </div>
        <div class="row">
          <div class="col-6 mt-5 ">
            <img src="{% static 'img/amazon.png' %}" alt="" style="width: 70%; margin-left: 78px;">
          </div>
          <div class="col-6 mt-5 ">
            <img src="{% static 'img/ebay.png' %}" alt="" style="width: 65%; height: 90%; margin-left: 103px;">
          </div>
        </div>
        <div class="row text-center mt-4">
          <div class="col">
            {% if create %}
              <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#amzCredentials">Link Amazon Seller Account</button>
            {% else %}
              <div class="btn-group dropright">
                <button type="button" class="btn btn-lg btn-success">
                  {{ email }}
                </button>
                <button type="button" class="btn btn-lg btn-success" data-target="#alert" data-toggle="modal">
                  <i class="fa fa-times" aria-hidden="true"></i>
                </button>
              </div>
              <div class="modal fade" id="alert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-body">
                      <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete ?</h5>
                      <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
                      <a href="{% url 'amazon:remove' %}" class="btn btn-danger">Yes</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}
          </div>
          <div class="col">
            {% if not ebayActive %}
              <form class="" action="{% url 'amazon:ebay' %}" method="post">{% csrf_token %}
                <button type="submit" id="amzFormButton" class="btn btn-lg btn-primary">Activate your eBay International Tracking</button>
              </form>
            {% else %}
              <button type="button" id="amzFormButton" class="btn btn-lg btn-primary disabled">Activate your eBay International Tracking</button>
            {% endif %}
          </div>
        </div>
      </div>
      {% include './snippets/AmazonCredentialsModal.html' with form=form%}
    {% endblock %}

amazon_seller/templates/seller/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% include 'seller/base/css.html' %}
  </head>
  <body style="background-color: #d8d8d8">
    <nav class="navbar navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="#"><img src="{% static 'img/amazonfbalogo.png' %}" alt="AfterShip logo" height="35px"></a>
      <div class="navbar-header">
          <a class="btn btn-light" href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i> Facebook</a>
          <form class="btn" action="{% url 'account_logout' %}" method="post">{% csrf_token %}
            <style media="screen">
              .submitLink {
                background-color: transparent;
                text-decoration: none;
                border: none;
                color: black;
                cursor: pointer;
              }
              submitLink:focus {
                outline: none;
              }
            </style>
            <input type="submit" class='submitLink' value='Logout'>
          </form>
      </div>

    </nav>
    <div id="wrapper" style="margin-top: 59px">
      {% include 'seller/snippets/top_navbar.html' %}
      <div id="page-content-wrapper">
        {% block main %}
        {% endblock %}
      </div>
      {% include 'seller/base/js.html' %}
      {% block script %}
      {% endblock %}
    </div>
  </body>
</html>

amazon_seller/templates/seller/help.html
{% extends './base.html' %}
{% load static %}
{% block main %}
  <div class="container">
    <div class="card rounded">
      <div class="card-body">
        <form action="{% url 'amazon:help' %}" method="POST">
          <div class="row">
            <h6 class="text-muted col-6">If you have any tracking numbers that were not uploaded and would like us to check them, Please fill in this form</h6>
          </div>
          <div class="row">
            <div class="col-9">
              <input type="text" class="form-control" name="tba_no" placeholder="Enter tracking number">
            </div>
            <div class="col-3">
              <input type="submit" class="form-control btn btn-success" value="Send">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

   
  <div class="container">
    <div class="card rounded">
      <div class="card-body">
        <form action="{% url 'amazon:help' %}" method="POST">
          {% csrf_token %}
          <div class="row">
            <h6 class="text-muted col-6">We are always ready to help you</h6>
          </div>
          <div class="row">
            <div class="col-9">
              <label>Email:</label>
              <input type="text" class="form-control" name="tba_no" placeholder="Enter your email">
              <label>Subject:</label>
              <input type="textarea" cols="40" rows="6" class="form-control" name="tba_no" placeholder="Enter your concern">
            </div>
          </br>
            <br>
             <input type="submit" class="form-control btn btn-success" style="width:10fr;" value="Send"></span>
            </div>
          </div>
        </form>
        
      </div>
    </div>
  </div>
{% endblock %}

amazon_seller/templates/seller/home.html
{% extends './base.html' %}
{% load seller_home_tags %}

{% block main %}
  <div class="container">
    {% if request.session.subscribed or object_list %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Transaction Id</th>
            <th scope="col">Plan</th>
            <th scope="col">Duration</th>
            <th scope="col">Amount</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
      {% for each in object_list %}
        <tr>
          <th scope="row">{{ each.transactionID }}</th>
          <td>{{ each.plan }}</td>
          <td>{{ each.duration }} days</td>
          <td>{{ each.amount }}</td>
          <td>{{ each.dateTime|dateToString }}</td>
          <td>{{ each.dateTime|addDays:each.duration }}</td>
          <td>
            {% if each.active %}
              <i class="fa fa-check" aria-hidden="true"></i>
            {% else %}
              <i class="fa fa-times" aria-hidden="true"></i>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h2 class="text-muted text-center">Welcome to Beezytrack</h2>
      <h3 class="text-muted text-center">Subscribe to enjoy our services</h4>
    {% endif %}
  </div>
{% endblock %}

amazon_seller/templates/seller/profile.html
{% extends './base.html' %}
{% load static %}
    {% block main %}
    <div class="container">
      <div class="row my-5  ">
        <div class="col-4">
          <div class="row">
            <img alt="150x150" src="{% static 'img/profile.png' %}" class='col-10' height="250px">
          </div>
          <a href="{% url 'account_change_password' %}"><button type="button" class="btn btn-info col-10 mt-1">Change Password</button></a>
        </div>
        <div class="col-8" style="font-size: 16px">
          <style media="screen">
            .submitLink {
              background-color: transparent;
              text-decoration: none;
              border: none;
              color: black;
              cursor: pointer;
            }
            submitLink:focus {
              outline: none;
            }
          </style>
          {% for key,value in obj_list.items %}
            <hr>
            <div class="">
              <form class="pencil row" action="#" method="post">{% csrf_token %}
                <div class='col-2 text-left text-secondary'>{{ key }}</div>
                <div class='col-9'>{{ value.label }}</div>
                <div class='col-1'><button type="submit" class='btn btn-dark submitLink'><i class="fa fa-pencil" aria-hidden="true"></i></button></div>
                <input type="hidden" name="key" value="{{ value.code }}">
                <input type="hidden" name="current" value="{{ value.label }}">
              </form>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endblock %}
    {% block script %}
      <script type="text/javascript" src="{% static 'js/update_profile.js' %}"></script>
    {% endblock %}

amazon_seller/templates/seller/subscription.html
{% extends './base.html' %}
{% load static %}
{% block main %}
  {% include './snippets/subscription.html' %}
{% endblock %}
{% block script %}
  <script src="{% static 'js/subscription.js' %}"></script>
{% endblock %}

amazon_seller/templates/seller/waste.html
<i class="fa fa-bars fa-1x" id="menu-toggle" style="cursor: pointer"></i>