amazon_seller/urls.py
from django.conf.urls import url
from .views import setupSellerAccount, home, profile, updateuser, remove, subscription_page, cancelSubscription, help_page, upgrade, setupEbayAccount
from orders.views import OrdersListView

urlpatterns = [
    url(r'^setup/$', setupSellerAccount, name='setup'),
    url(r'^home/$', home, name='home'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^updateuser/$', updateuser, name='updateuser'),
    url(r'^orders/$', OrdersListView.as_view(), name='orders'),
    url(r'^remove/$', remove, name='remove'),
    url(r'^subscription/$', subscription_page, name='subscription'),
    url(r'^subscription/cancel$', cancelSubscription, name='cancelSubscription'),
    url(r'^help$', help_page, name='help'),
    url(r'^ebay$', setupEbayAccount, name='ebay'),
    #url(r'^upgrade$', upgrade, name='upgrade'),
]

buyers/urls.py
from django.conf.urls import url
from orders.views import OrdersSearchView
from .views import learn_more, contact_page, search_tool_page

urlpatterns = [
    #url(r'^contact/$', contact_page, name='contact'),
    url(r'^home/$', OrdersSearchView.as_view(), name='home'),
    url(r'^learnmore/$', learn_more, name='learn_more'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^searchTool/$', search_tool_page, name='search_tool'),
]

trackbot/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^amazon/', include(("amazon_seller.urls", "amazon"), namespace='amazon')),
    url(r'^buyers/', include(("buyers.urls", "buyers"), namespace='buyers')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include(('payment.urls', 'payment'), namespace='payment')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon_seller/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class SellerAccount(models.Model):
    user     = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    email    = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.email

class EbayAccount(models.Model):
    user    = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    activate = models.BooleanField()

    def __str__(self):
        return self.user.email

amazon_seller/forms.py
from django import forms

class AmazonLoginForm(forms.Form):
    email_widget = forms.TextInput(
        attrs={'type': 'email','placeholder':('E-mail address'), 'autofocus': 'autofocus', 'class': 'form-control'}
    )
    email = forms.EmailField(label=(""), widget=email_widget)

    password_widget = forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    )
    password = forms.CharField(label=(""), widget=password_widget)

amazon_seller/views.py
from django.shortcuts import render, redirect, reverse
from .models import SellerAccount, EbayAccount
from django.http import HttpResponse
from .forms import AmazonLoginForm
from .models import SellerAccount
from django.contrib.auth import get_user_model
from paypal.standard.forms import PayPalPaymentsForm
from payment.models import Transactions
from django.utils import timezone
from payment.utils import checkSubscription
from payment.models import Transactions
from datetime import timedelta
from collections import defaultdict
from django.core.mail import send_mail

def upgrade(request):
    pass

def help_page(request):
    if request.user.is_authenticated:
        if request.POST:
            tba = request.POST.get('tba_no')
            #message = 'Following tracking number of '+request.user.email+' is missing: '+tba
            # send_mail(
            #     'Re. Tracking Number',
            #     message,
            #     'wjeff.fortin@yahoo.com',
            #     ['info@beezytrack.com'],
            #     fail_silently=False,
            #     auth_user='wjeff.fortin@yahoo.com',
            #     auth_password='Beezytrack'
            # )
        return render(request, 'seller/help.html', {})
    return redirect('/accounts/login')

def remove(request):
    if request.user.is_authenticated:
        account = SellerAccount.objects.filter(user=request.user)
        if account:
            account.delete()
            return redirect('/amazon/setup')
    return redirect('/amazon/setup')

def profile(request):
    if request.user.is_authenticated:
        context = {}
        user = request.user
        context['Username'] = { 'label': user.username, 'code': 'username' }
        context['Email'] = {'label': user.email, 'code': 'email' }
        context['First Name'] = { 'label': user.first_name, 'code': 'first_name' }
        context['Last Name'] = { 'label': user.last_name, 'code': 'last_name' }
        return render(request, 'seller/profile.html', {'obj_list' : context})
    else:
        return redirect('/accounts/login')

def updateuser(request):
    if request.user.is_authenticated and request.is_ajax:
        user = request.user
        for key, values in request.POST.items():
            setattr(user, key, values)
            user.save()
        return HttpResponse('Done')
    else:
        return redirect('/accounts/login')

def setupSellerAccount(request):
    if request.user.is_authenticated:
        if request.session.get('subscribed'):
            form = AmazonLoginForm(request.POST or None)
        else:
            form = False
        context = {}
        account = SellerAccount.objects.filter(user=request.user)
        create = True
        if account:
            create = False
            context['email'] = account[0].email
        if request.POST and request.session.get('subscribed'):
            if form.is_valid():
                print(form.cleaned_data)
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password')
                obj = SellerAccount.objects.get_or_create(
                    user = request.user,
                    email = email,
                    password = password
                )
                return redirect('/amazon/setup')
        context['form'] = form
        context['create'] = create
        inst = EbayAccount.objects.filter(user = request.user)
        if inst:
            context['ebayActive'] = True
        return render(request, 'seller/addThirdPartyAccounts.html', context)
    else:
        return redirect('/accounts/login')

def setupEbayAccount(request):
    if request.user.is_authenticated:
        context = {}
        if request.POST:
            obj = EbayAccount(
                user = request.user,
                activate = True
            )
            obj.save()
            context['notify'] = True
        if request.session.get('subscribed'):
            form = AmazonLoginForm(request.POST or None)
        else:
            form = False
        account = SellerAccount.objects.filter(user=request.user)
        create = True
        if account:
            create = False
            context['email'] = account[0].email
        context['form'] = form
        context['create'] = create
        inst = EbayAccount.objects.filter(user = request.user)
        if inst:
            context['ebayActive'] = True
        return render(request, 'seller/addThirdPartyAccounts.html', context)
    else:
        return redirect('/accounts/login')

def home(request):
    if request.user.is_authenticated:
        context = {}
        qs = Transactions.objects.filter(user = request.user)
        context['object_list'] = qs
        return render(request, 'seller/home.html', context)
    else:
        return redirect('/accounts/login')

def subscription_page(request):
    if request.user.is_authenticated:
        form = {}
        plans = {
            'Beezytrack': {
                'mo': 4.99,
                'yr': 49.99
            },
            'Pro Drop Shipper': {
                'mo': 4.99,
                'yr': 49.99
            },
            'Combo (Beezytrack + Pro Drop Shipper)': {
                'mo': 9.98,
                'yr': 99.98
            }
        }
        result = checkSubscription(request)
        if result.get('status'):
            obj = result.get('transaction')
            duration_int = result.get('duration')
            flag=0
            if duration_int == 30:
                duration_str = 'mo'
            elif duration_int == 365:
                duration_str = 'yr'
            for planName, attrs in plans.items():
                temp = {}
                for duration, amount in attrs.items():
                    if obj.plan == planName and duration_str == duration:
                        temp[duration] = {'status': True, 'amount': {'value': amount}, 'sandbox': "active", 'daysLeft': result.get('days-left'), 'daysPercent': (duration_int - result.get('days-left'))/duration_int*100 }
                        flag=1
                    else:
                        temp[duration] = {'status': False, 'sandbox': '', 'amount': {'value': amount}}
                if flag:
                    temp['active'] = duration_int
                    flag = 0
                form[planName] = temp
        else:
            for planName, attrs in plans.items():
                temp = {}
                for duration, amount in attrs.items():
                    paypal_dict = {
                        'business': 'nikhil.thakur929@gmail.com',
                        'amount': amount,
                        'item_name': planName,
                        'invoice': duration, # it should be unique
                        'currency_code': 'USD',
                        'notify_url': request.build_absolute_uri(reverse('paypal-ipn')),
                        'return_url': request.build_absolute_uri(reverse('payment:done')),
                        'cancel_return': request.build_absolute_uri(reverse('payment:cancelled')),
                        'rm': 2,
                        'custom': request.user.email
                    }
                    temp[duration] = (PayPalPaymentsForm(initial=paypal_dict))
                form[planName] = temp
        return render(request, "seller/subscription.html", {'form': form})
    else:
        return redirect('/accounts/login')

def cancelSubscription(request):
    if request.user.is_authenticated and request.session.get('subscribed') == True:
        user = request.user
        qs = Transactions.objects.filter(user=user, active=True)[0]
        setattr(qs, 'active', False)
        qs.save()
        return redirect('/amazon/subscription')
    else:
        return redirect('/accounts/login')

amazon_seller/templates/seller/snippets/AmazonCredentialsModal.html
<div class="modal fade" id="amzCredentials" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        {% if form %}
          <h5 class="modal-title" id="exampleModalLabel">Enter Amazon Credentials</h5>
        {% else %}
          <h5>Sorry!! Subscribe to use this service</h5>
        {% endif %}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if form %}
        <form class="" action="{% url 'amazon:setup' %}" method="post">{% csrf_token %}
          <div class="modal-body">
            {{ form }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
</div>

amazon_seller/templates/seller/snippets/subscription-decision.html
{% if request.user.is_authenticated %}
  {% if form.sandbox == 'active' %}
    <div class="progress col-10" style="height: 30px">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow='75' aria-valuemin="0" aria-valuemax="100" style="width: {{ form.daysPercent }}%"></div>
    </div>
    {{ form.daysLeft }} days left
  {% else %}
    <div class="">
      {{ form.sandbox }}
    </div>
  {% endif %}
{% endif %}

amazon_seller/templates/seller/snippets/subscription.html
<div class="container mt-4">
  {% if not request.session.subscribed %}
    <h2 class="text-center">Subscribe to track your orders</h2>
  {% endif %}
  <div class="card-deck mt-3">
    {% for planName, values in form.items %}
      {% include './subscriptionCards.html' with form=values title=planName content="" %}
    {% endfor %}
  </div>
</div>

amazon_seller/templates/seller/snippets/subscriptionCards.html
<div class="card text-center">
  {% if form.active %}
    <div class="card-header">
        <button type="button" class="close" data-target="#cancelSubscription" data-toggle="modal">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal fade" id="cancelSubscription" tabindex="-1" role="dialog" aria-labelledby="cancelSubscription" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to cancel your subscription ?</h5>
                <button type="button" class="btn btn-success" data-dismiss="modal">No</button>
                <a href="{% url 'amazon:cancelSubscription' %}" class="btn btn-danger">Yes</a>
              </div>
            </div>
          </div>
        </div>
    </div>
  {% endif %}
  <div class="card-body">
    <h3 class="card-title">{{ title }}</h3>
    <p class="card-text">{{ content }}</p>
    {% for key, values in form.items %}
      {% if key != 'active' %}
        <hr>
        <div class="row mt-3 justify-content-center">
          <h4 class="card-title col-5">{{ values.amount.value }}/{{ key }}</h4>
          {% include './subscription-decision.html' with form=values %}
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>

amazon_seller/templates/seller/snippets/temp.html
{% for planName, values in form.items %}
  {% include './subscriptionCards.html' with form=values title="Business" content="This is a longer card" %}
{% endfor %}


<div class="card-body">
  <h1 class="card-title">{{ title }}</h1>
  <p class="card-text">{{ content }}</p>
  {% for each in form %}
  <h2 class="card-title">{{ each.amount.value }}</h2>
  {% include './subscription-decision.html' with form=each %}
  {% endfor %}
</div>


{% include './subscriptionCards.html' with form=form1 title="Starter" amount="$9.99/mo" content="This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer." %}
{% include './subscriptionCards.html' with form=form2 title="Professional" amount="$14.99/mo" content="This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer." %}
{% include './subscriptionCards.html' with form=form3 title="Business" amount="$19.99/mo" content="This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer." %}

amazon_seller/templates/seller/snippets/top_navbar.html
{% url 'amazon:home' as home_url %}
{% url 'amazon:setup' as setup_url %}
{% url 'amazon:orders' as orders_url %}
{% url 'amazon:profile' as profile_url %}
{% url 'amazon:subscription' as subscription_url %}
{% url 'amazon:help' as help_url %}

<aside>
  <div id="sidebar-wrapper">
     <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
        <li class="{% if request.path == home_url %}active{% endif %}">
           <a href="{% url 'amazon:home' %}">Home</a>
        </li>
        <li class="{% if request.path == setup_url %}active{% endif %}">
           <a href="{% url 'amazon:setup' %}">Link Account</a>
        </li>
        {% if request.session.subscribed %}
          <li class="{% if request.path == orders_url %}active{% endif %}">
             <a href="{% url 'amazon:orders' %}">View Orders</a>
          </li>
        {% endif %}
        <li class="{% if request.path == profile_url %}active{% endif %}">
           <a href="{% url 'amazon:profile' %}">Profile</a>
        </li>
        <li class="{% if request.path == subscription_url %}active{% endif %}">
          {% if request.session.subscribed %}
            <a href="{% url 'amazon:subscription' %}">View Plan / Cancel Plan</a>
          {% else %}
            <a href="{% url 'amazon:subscription' %}">Subscribe</a>
          {% endif %}
        </li>
        <li class="{% if request.path == help_url %}active{% endif %}">
           <a href="{% url 'amazon:help' %}">Help</a>
        </li>
     </ul>
  </div>
</aside>