buyers/urls.py
from django.conf.urls import url
from orders.views import OrdersSearchView
from .views import learn_more, contact_page, search_tool_page

urlpatterns = [
    #url(r'^contact/$', contact_page, name='contact'),
    url(r'^home/$', OrdersSearchView.as_view(), name='home'),
    url(r'^learnmore/$', learn_more, name='learn_more'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^searchTool/$', search_tool_page, name='search_tool'),
]

trackbot/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^amazon/', include(("amazon_seller.urls", "amazon"), namespace='amazon')),
    url(r'^buyers/', include(("buyers.urls", "buyers"), namespace='buyers')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include(('payment.urls', 'payment'), namespace='payment')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyers/models.py
from django.db import models

# Create your models here.

buyers/forms.py
from django import forms
from django.core.exceptions import ValidationError


class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter your name"
            }
        ),
        label=("Your Name:")
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Email"
            }
        ), label=("Email:")
    )
    subject = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Subject"
            }
        ), label=("Subject:")
    )
    CHOICES = (('India', 'India'), ('America', 'America'), ('Japan', 'Japan'))
    country = forms.ChoiceField(
        choices = CHOICES,
        widget=forms.Select(attrs={'class':'form-control'})
    )
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "placeholder": "Message",
                "rows": "6",
            }
        ), label=("Message:")
    )

    def clean_email(self):
        e = self.cleaned_data['email']
        if not e:
            raise ValidationError("Email is required")
        return e

buyers/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ContactForm
from django.core.mail import send_mail

def learn_more(request):
    return render(request, 'buyers/learn_more.html', {})

def search_tool_page(request):
    return render(request, 'buyers/search_tool.html', {})

def contact_page(request):
    form = ContactForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            country = form.cleaned_data['country']
            message = form.cleaned_data['message']
            # send_mail(
            #     subject,
            #     message,
            #     'wjeff.fortin@yahoo.com',
            #     ['info@beezytrack.com'],
            #     fail_silently=False,
            #     auth_user='wjeff.fortin@yahoo.com',
            #     auth_password='Beezytrack'
            # )
            return render(request, 'buyers/contact.html', {'form': form, 'status': True})
    return render(request, 'buyers/contact.html', {'form': form})

buyers/templates/buyers/base/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/home_contact.css' %}">

buyers/templates/buyers/base/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

buyers/templates/buyers/base/top_navbar.html
{% url 'buyers:home' as home_url %}
{% url 'buyers:learn_more' as learn_url %}
{% url 'buyers:search_tool' as search_url %}
{% url 'buyers:contact' as contact_url %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#282828">
  <a class="navbar-brand" href="#"><img src="{% static 'img/check2.png' %}" alt="AfterShip logo" height="50px" style="background-color:"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item navbar-brand {% if request.path == home_url %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900" href="{% url 'buyers:home' %}">Home</a>
        </li>
        <li class="nav-item navbar-brand {% if request.path == account_login %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900" href="{% url 'account_login' %}">Beezytrack Login</a>
        </li>
        <li class="nav-item navbar-brand {% if request.path == learn_url %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900"  href="{% url 'buyers:learn_more' %}">Learn More</a>
        </li>
        <li class="nav-item navbar-brand {% if request.path == search_url %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900" href="{% url 'buyers:search_tool' %}">Search Tool</a>
        </li>
        <li class="nav-item navbar-brand {% if request.path == account_signup %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900" href="{% url 'account_signup' %}">Signup</a>
        </li>
        <li class="nav-item navbar-brand {% if request.path == contact_url %}active{% endif %}">
            <a class='nav-link font-weight-bold' style="color: #FF9900" href="{% url 'buyers:contact' %}">Contact Us</a>
        </li>
      </ul>
  </div>
</nav>